$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Assemble-Schema.ps1
#
# Assembles the committed schema artefacts into a single build script.
# This script does not connect to a database.
# ---------------------------------------------------------------------------

$SchemaRoot = "database/schema"
$BuildRoot  = "database/build"
$OutputFile = Join-Path $BuildRoot "schema.sql"

$Sections = @(
  @{ Name = "Tables";      Path = "$SchemaRoot/tables" },
  @{ Name = "Views";       Path = "$SchemaRoot/views" },
  @{ Name = "Constraints"; Path = "$SchemaRoot/constraints" }
)

# --- Validation -------------------------------------------------------------

foreach ($section in $Sections) {
  if (-not (Test-Path $section.Path)) {
    throw "Schema section missing: $($section.Path)"
  }
}

New-Item -ItemType Directory -Force -Path $BuildRoot | Out-Null

# --- Assembly ---------------------------------------------------------------

$buffer = @()

$buffer += "-- ------------------------------------------------------------------"
$buffer += "-- Schema build generated from committed artefacts"
$buffer += "-- Do not edit this file manually"
$buffer += "-- ------------------------------------------------------------------"
$buffer += ""

foreach ($section in $Sections) {

  $files = Get-ChildItem $section.Path -Filter *.sql | Sort-Object Name

  if ($files.Count -eq 0) {
    Write-Warning "No SQL files found in $($section.Path)"
    continue
  }

  $buffer += ""
  $buffer += "-- === $($section.Name) ==============================================="
  $buffer += ""

  foreach ($file in $files) {
    $buffer += "-- Source: $($file.FullName)"
    $buffer += Get-Content $file.FullName -Raw
    $buffer += ""
  }
}

# --- Write output -----------------------------------------------------------

$buffer -join "`n" | Out-File -Encoding utf8 $OutputFile

Write-Host "Schema assembled: $OutputFile"
